### ISSUE TITLE
Error with cpanel 58 PHP path on install

### ISSUE THREAD

**Issue by rdetwiler** [cloudflare/CloudFlare-CPanel#98]
Hello,
Noticed our users were having trouble accessing their CF control panel. This was in the logs:

```
Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cloudflare/proxy.live.php. at cpanel.pl line 4904.
[2016-07-12 14:46:56 -0400] warn [cpsrvd] The subprocess (cpanel (cpanel)) exited with an error: The subprocess reported error number 10 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 156.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x2a2c8b8)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 71
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x2a2c8b8), "subprocess_name", "cpanel (cpanel)", "subprocess_read_handle", IO::Handle=GLOB(0x2a2c5d0), "subprocess_write_handle", IO::Handle=GLOB(0x2a14810), "api_type", "html", ...) called at cpsrvd.pl line 6369
	cpanel::cpsrvd::cpHandler("app", "cpanel", "document", "./frontend/paper_lantern/cloudflare/proxy.live.php") called at cpsrvd.pl line 2315
	cpanel::cpsrvd::dodoc_cpaneld() called at cpsrvd.pl line 1550
	cpanel::cpsrvd::dodoc(HASH(0xea46c0)) called at cpsrvd.pl line 1315
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 807
	cpanel::cpsrvd::script() called at cpsrvd.pl line 314
PHP Warning:  require_once(cloudflare/vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 2
PHP Fatal error:  require_once(): Failed opening required 'cloudflare/vendor/autoload.php' (include_path='/usr/local/cpanel/3rdparty/php/56/lib/php:.') in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/proxy.live.php on line 2
[2016-07-12 14:47:41 -0400] die [Internal Death while parsing [live php] 800446] Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cloudflare/proxy.live.php. at cpanel.pl line 4904.
 at cpanel.pl line 4904.
	cpanel::cpanel::setup_external_engine() called at cpanel.pl line 792
	cpanel::cpanel::script("cpanel::cpanel", "./frontend/paper_lantern/cloudflare/proxy.live.php") called at cpanel.pl line 295


Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cloudflare/proxy.live.php. at cpanel.pl line 4904.
[2016-07-12 14:47:42 -0400] warn [cpsrvd] The subprocess (cpanel (cpanel)) exited with an error: The subprocess reported error number 10 when it ended. at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 156.
	Cpanel::Server::Handlers::SubProcess::_report_subprocess_errors(Cpanel::Server::Handlers::SubProcess=HASH(0x2a1ba98)) called at /usr/local/cpanel/Cpanel/Server/Handlers/SubProcess.pm line 71
	Cpanel::Server::Handlers::SubProcess::handler(Cpanel::Server::Handlers::SubProcess=HASH(0x2a1ba98), "subprocess_name", "cpanel (cpanel)", "subprocess_read_handle", IO::Handle=GLOB(0x2a2ccd8), "subprocess_write_handle", IO::Handle=GLOB(0x2a1b9c0), "api_type", "html", ...) called at cpsrvd.pl line 6369
	cpanel::cpsrvd::cpHandler("app", "cpanel", "document", "./frontend/paper_lantern/cloudflare/proxy.live.php") called at cpsrvd.pl line 2315
	cpanel::cpsrvd::dodoc_cpaneld() called at cpsrvd.pl line 1550
	cpanel::cpsrvd::dodoc(HASH(0xea46c0)) called at cpsrvd.pl line 1315
	cpanel::cpsrvd::handle_one_connection() called at cpsrvd.pl line 807
	cpanel::cpsrvd::script() called at cpsrvd.pl line 314
[2016-07-12 14:50:18 -0400] info [install_plugin] Installing to paper_lantern
[2016-07-12 14:50:18 -0400] info [install_plugin] Running sprite_generator
PHP Warning:  require_once(cloudflare/vendor/autoload.php): failed to open stream: No such file or directory in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 2
PHP Fatal error:  require_once(): Failed opening required 'cloudflare/vendor/autoload.php' (include_path='/usr/local/cpanel/3rdparty/php/56/lib/php:.') in /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php on line 2
[2016-07-12 14:52:42 -0400] die [Internal Death while parsing [live php] 803206] Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cloudflare/index.live.php. at cpanel.pl line 4904.
 at cpanel.pl line 4904.
	cpanel::cpanel::setup_external_engine() called at cpanel.pl line 792
	cpanel::cpanel::script("cpanel::cpanel", "./frontend/paper_lantern/cloudflare/index.live.php") called at cpanel.pl line 295
```

Looking at the install script, it appears to install the vendor folder to:
`/usr/local/cpanel/3rdparty/php/54/lib/php/cloudflare/vendor/`
but on our system, we default to 56
`/usr/local/cpanel/3rdparty/php/56/lib/php/`
Issuing a 
`cp -R /usr/local/cpanel/3rdparty/php/54/lib/php/cloudflare/ /usr/local/cpanel/3rdparty/php/56/lib/php/ `
fixed the issue for us, but just wanted to let you know you may want to update the script to check for different default PHP versions.

Thanks!
Ray

**Comment by jwineman** [comment]
Hi,

Thanks for letting us know about this!  Can you confirm which version of cPanel you're using?  Is it cPanel 58?  I noticed in the change log they upgraded from PHP 5.4 to 5.6 and wanted to confirm you weren't on some custom installation with multiple versions installed.  You ONLY have 5.6 installed correct?

Thanks,
John

**Comment by jwineman** [comment]
Tracking internally PI-676.

**Comment by rdetwiler** [comment]
Hello, Yes were only using 5.6 and correct cPanel 58. Seems that we only noticed this after the upgrade so I'm betting the version update by cpanel is why. 

Thanks for responding so quickly!

**Comment by jwineman** [comment]
Fixed.
https://github.com/cloudflare/CloudFlare-CPanel/pull/100
https://github.com/cloudflare/CloudFlare-CPanel/pull/101

**Comment by jwineman** [comment]
Released in 6.0.5

**Comment by adtastic** [comment]
ok seems we are having the same problem now with cPanel58 our customers are getting the error Child failed to make LIVEAPI connection to cPanel. Seems this has been fixed by cloudflare but  I am unclear what i need to do in order to fix it on my end.

**Comment by jwineman** [comment]
For starters please run:
```
cat /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/config.js | grep version
```
if your version is less than 6.0.5 then please manually reinstall the plugin with the command on the README.  If you are already on 6.0.5 please file a support ticket with http://support.cloudflare.com/ as we've had a few customers who are still experiencing isssues and we're in the process of debugging the root cause.

Thanks,
John

**Comment by adtastic** [comment]
Thanks for the response. Yes I have 6.0.4. As to manually reinstall, can I not just run the update: /usr/local/cpanel/bin/cloudflare_update.sh?

**Comment by jwineman** [comment]
If you're on 6.0.4 you should be able to run cloudflare_update.sh.

**Comment by Radeyo** [comment]
jwineman,

This still seems to be occurring. When the Cloudflare plugin is installed on a cPanel server earlier than v58, then updated to the latest version, the LIVEAPI connection failure error when clicking Cloudflare from cPanel occurs. I've copied the error below.

Re-installing the plugin fixes this, but the problem described in the original report on this issue still seems to exist.

[2016-09-14 16:30:17 -0400] die [Internal Death while parsing [live php] 13146] Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cloudflare/index.live.php. at cpanel.pl line 4904.
 at cpanel.pl line 4904.
        cpanel::cpanel::setup_external_engine() called at cpanel.pl line 792
        cpanel::cpanel::script("cpanel::cpanel", "./frontend/paper_lantern/cloudflare/index.live.php") called at cpanel.pl line 295


Child failed to make LIVEAPI connection to cPanel from: ./frontend/paper_lantern/cloudflare/index.live.php. at cpanel.pl line 4904.

**Comment by jwineman** [comment]
Hi @Radeyo,

I think this is a cPanel error, not a CloudFlare error.  Can you run:
```
ls -al /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php
```
and ensure it looks like this:
```
-rwxr-xr-x. 1 root root 3440 Sep 11 02:12 /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php
```
If it doesn't, try updating the permissions.  If it does I think you'll need to open a ticket with cPanel.  

That error means that (this line)[https://github.com/cloudflare/CloudFlare-CPanel/blob/master/index.live.php#L3] is failing, which is outside the plugin's control.

Thanks,
John

**Comment by Radeyo** [comment]
@jwineman 

Looks to be OK after reinstalling the plugin after the cPanel update. I appreciate the quick follow-up.

[/]# ls -al /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php
-rwxr-xr-x 1 root root 3440 Sep 15 09:31 /usr/local/cpanel/base/frontend/paper_lantern/cloudflare/index.live.php*
